#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pluggy
Version  : 1.0.0
Release  : 81
URL      : https://files.pythonhosted.org/packages/a1/16/db2d7de3474b6e37cbb9c008965ee63835bba517e22cdb8c35b5116b5ce1/pluggy-1.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/a1/16/db2d7de3474b6e37cbb9c008965ee63835bba517e22cdb8c35b5116b5ce1/pluggy-1.0.0.tar.gz
Summary  : plugin and hook calling mechanisms for python
Group    : Development/Tools
License  : MIT
Requires: pypi-pluggy-license = %{version}-%{release}
Requires: pypi-pluggy-python = %{version}-%{release}
Requires: pypi-pluggy-python3 = %{version}-%{release}
Requires: pypi(importlib_metadata)
BuildRequires : buildreq-distutils3
BuildRequires : pypi(importlib_metadata)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi(wheel)

%description
====================================================
pluggy - A minimalist production ready plugin system
====================================================

%package license
Summary: license components for the pypi-pluggy package.
Group: Default

%description license
license components for the pypi-pluggy package.


%package python
Summary: python components for the pypi-pluggy package.
Group: Default
Requires: pypi-pluggy-python3 = %{version}-%{release}

%description python
python components for the pypi-pluggy package.


%package python3
Summary: python3 components for the pypi-pluggy package.
Group: Default
Requires: python3-core
Provides: pypi(pluggy)
Requires: pypi(importlib_metadata)

%description python3
python3 components for the pypi-pluggy package.


%prep
%setup -q -n pluggy-1.0.0
cd %{_builddir}/pluggy-1.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641543281
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pluggy
cp %{_builddir}/pluggy-1.0.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pluggy/67d360a32d3b3a723998ca8ac1fae5a242afbce7
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pluggy/67d360a32d3b3a723998ca8ac1fae5a242afbce7

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
